apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-worker
spec:
  template:
    spec:
      terminationGracePeriodSeconds: 300
      containers:
        - name: lms-worker
          args:
            - celery
            - --app=lms.celery
            - worker
            - --loglevel=info
            - --concurrency=1
            - --hostname=edx.lms.core.default.%%h
            - --max-tasks-per-child=1
            - --prefetch-multiplier=1
            - --exclude-queues=edx.cms.core.default
