apiVersion: v1
kind: Secret
metadata:
  name: openedx-image-pull-secret
  namespace: {{ K8S_NAMESPACE }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {{ DRYDOCK_REGISTRY_CREDENTIALS }}
