apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: {{ K8S_NAMESPACE }}

resources:
- base
- extensions
{{ patch("drydock-kustomization-resources") }}

{%- if DRYDOCK_ENABLE_OVERRIDES  %}
patchesStrategicMerge:
{%- if DRYDOCK_ENABLE_RESOURCE_MANAGEMENT or patch("drydock-overrides") or DRYDOCK_NEWRELIC %}
-  extensions/overrides.yml
{%- endif %}
{{ patch("drydock-kustomization-patches") }}
{%- endif %}
