{%- if DRYDOCK_ENABLE_RESOURCE_MANAGEMENT -%}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms
spec:
  template:
    spec:
      containers:
        - name: lms
          resources:
            limits:
              cpu: "{{ DRYDOCK_LMS_LIMIT_CPU }}"
              memory: "{{ DRYDOCK_LMS_LIMIT_MEMORY }}"
            requests:
              cpu: "{{ DRYDOCK_LMS_REQUEST_CPU }}"
              memory: "{{ DRYDOCK_LMS_REQUEST_MEMORY }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms
spec:
  template:
    spec:
      containers:
        - name: cms
          resources:
            limits:
              cpu: "{{ DRYDOCK_CMS_LIMIT_CPU }}"
              memory: "{{ DRYDOCK_CMS_LIMIT_MEMORY }}"
            requests:
              cpu: "{{ DRYDOCK_CMS_REQUEST_CPU }}"
              memory: "{{ DRYDOCK_CMS_REQUEST_MEMORY }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-worker
spec:
  template:
    spec:
      containers:
        - name: lms-worker
          resources:
            limits:
              cpu: "{{ DRYDOCK_LMS_WORKER_LIMIT_CPU }}"
              memory: "{{ DRYDOCK_LMS_WORKER_LIMIT_MEMORY }}"
            requests:
              cpu: "{{ DRYDOCK_LMS_WORKER_REQUEST_CPU }}"
              memory: "{{ DRYDOCK_LMS_WORKER_REQUEST_MEMORY }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-worker
spec:
  template:
    spec:
      containers:
        - name: cms-worker
          resources:
            limits:
              cpu: "{{ DRYDOCK_CMS_WORKER_LIMIT_CPU }}"
              memory: "{{ DRYDOCK_CMS_WORKER_LIMIT_MEMORY }}"
            requests:
              cpu: "{{ DRYDOCK_CMS_WORKER_REQUEST_CPU }}"
              memory: "{{ DRYDOCK_CMS_WORKER_REQUEST_MEMORY }}"
---
{% endif -%}
{{ patch("drydock-overrides") }}
