{% if RUN_LMS %}
---
apiVersion: v1
kind: Service
metadata:
  name: lms-debug
  namespace: {{ K8S_NAMESPACE }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app.kubernetes.io/name: lms-debug
  type: ClusterIP
{% endif %}
{% if RUN_CMS %}
---
apiVersion: v1
kind: Service
metadata:
  name: cms-debug
  namespace: {{ K8S_NAMESPACE }}
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app.kubernetes.io/name: cms-debug
  type: ClusterIP
{% endif %}
