apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms
spec:
  template:
    spec:
      containers:
        - name: lms
          lifecycle:
            preStop:
              exec:
                command:
                - "sleep"
                - "30"
          readinessProbe: # Make sure the pod can answer traffic before handling any requests
          # Only route traffic if the pod is alive, and has passed two succesful checks (max 10s)
            successThreshold: 2
            failureThreshold: 2
            periodSeconds: 10
            timeoutSeconds: 5
            httpGet:
              path: /heartbeat
              port: 8000
              httpHeaders:
                - name: Host
                  value: {{ LMS_HOST }}
      terminationGracePeriodSeconds: 60
