---
apiVersion: v1
kind: Service
metadata:
  name: lms-debug
  namespace: {{ K8S_NAMESPACE }}
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app.kubernetes.io/name: lms-debug
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: cms-debug
  namespace: {{ K8S_NAMESPACE }}
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app.kubernetes.io/name: cms-debug
  type: ClusterIP
