apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-worker
spec:
  template:
    spec:
      containers:
        - name: cms-worker
          resources:
            limits:
              cpu: "{{ DRYDOCK_CMS_WORKER_LIMIT_CPU }}"
              memory: "{{ DRYDOCK_CMS_WORKER_LIMIT_MEMORY }}"
            requests:
              cpu: "{{ DRYDOCK_CMS_WORKER_REQUEST_CPU }}"
              memory: "{{ DRYDOCK_CMS_WORKER_REQUEST_MEMORY }}"
