apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms
spec:
  template:
    spec:
      containers:
        - name: cms
          resources:
            limits:
              cpu: "{{ DRYDOCK_CMS_LIMIT_CPU }}"
              memory: "{{ DRYDOCK_CMS_LIMIT_MEMORY }}"
            requests:
              cpu: "{{ DRYDOCK_CMS_REQUEST_CPU }}"
              memory: "{{ DRYDOCK_CMS_REQUEST_MEMORY }}"
