apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-worker
spec:
  template:
    spec:
      containers:
        - name: lms-worker
          resources:
            limits:
              cpu: "{{ DRYDOCK_LMS_WORKER_LIMIT_CPU }}"
              memory: "{{ DRYDOCK_LMS_WORKER_LIMIT_MEMORY }}"
            requests:
              cpu: "{{ DRYDOCK_LMS_WORKER_REQUEST_CPU }}"
              memory: "{{ DRYDOCK_LMS_WORKER_REQUEST_MEMORY }}"
