apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms
spec:
  template:
    spec:
      containers:
        - name: lms
          resources:
            limits:
              cpu: "{{ DRYDOCK_LMS_LIMIT_CPU }}"
              memory: "{{ DRYDOCK_LMS_LIMIT_MEMORY }}"
            requests:
              cpu: "{{ DRYDOCK_LMS_REQUEST_CPU }}"
              memory: "{{ DRYDOCK_LMS_REQUEST_MEMORY }}"
