apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower-edxapp
  labels:
    app.kubernetes.io/name: flower-edxapp
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: flower-edxapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flower-edxapp
    spec:
      containers:
        - name: flower-edxapp
          image: docker.io/mher/flower:0.9.5
          ports:
            - containerPort: 5555
          env:
          - name: CELERY_BROKER_URL
            value: redis://{{ REDIS_USERNAME }}:{{ REDIS_PASSWORD }}@{{ REDIS_HOST }}:{{ REDIS_PORT }}/{{ OPENEDX_CELERY_REDIS_DB }}
          - name: FLOWER_PORT
            value: "5555"
