{%- if MINIO_DOCKER_IMAGE is defined %}
apiVersion: batch/v1
kind: Job
metadata:
  name: drydock-minio-job
  labels:
    drydock.io/component: job
    drydock.io/target-service: minio
    drydock.io/runner-service: minio
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: minio
          image: {{ MINIO_MC_DOCKER_IMAGE }}
          command: ["/bin/sh", "-c"]
          args:
          - |
            mc config host add minio http://minio:9000 {{ OPENEDX_AWS_ACCESS_KEY }} {{ OPENEDX_AWS_SECRET_ACCESS_KEY }} --api s3v4
            mc mb --ignore-existing minio/{{ MINIO_BUCKET_NAME }} minio/{{ MINIO_FILE_UPLOAD_BUCKET_NAME }} minio/{{ MINIO_VIDEO_UPLOAD_BUCKET_NAME }}

            # Make common file upload bucket public (e.g: for forum image upload)
            mc policy set public minio/{{ MINIO_BUCKET_NAME }}
          env:
            - name: MINIO_ROOT_USER
              value: "{{ OPENEDX_AWS_ACCESS_KEY }}"
            - name: MINIO_ROOT_PASSWORD
              value: "{{ OPENEDX_AWS_SECRET_ACCESS_KEY }}"
{%- endif %}