---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-cms
  namespace: {{ K8S_NAMESPACE }}
  annotations:
    {%- if DRYDOCK_AUTO_TLS and not DRYDOCK_CUSTOM_CERTS%}
    cert-manager.io/issuer: letsencrypt
    {%- endif %}
spec:
  ingressClassName: {{ DRYDOCK_INGRESS_CLASS }}
  rules:
  - host: {{ CMS_HOST }}
    http:
      paths:
{%- if MFE_DOCKER_IMAGE is defined %}
{%- for app_name, app in iter_mfes() %}
{%- if app_name == "authoring" %}
      - pathType: Prefix
        path: "/course-authoring"
        backend:
          service:
            name: caddy
            port:
              number: 80
      - pathType: Prefix
        path: "/{{app_name}}"
        backend:
          service:
            name: caddy
            port:
              number: 80
{%- endif %}
{%- endfor %}
{%- endif %}
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: caddy
            port:
              number: 80
  {%- if DRYDOCK_AUTO_TLS or DRYDOCK_CUSTOM_CERTS %}
  tls:
  - hosts:
    - {{ CMS_HOST }}
    {%- if DRYDOCK_CUSTOM_CERTS %}
    secretName: {{ DRYDOCK_CUSTOM_CERTS["secret_name"]|default("custom-tls-certs") }}
    {%- else %}
    secretName: cms-host-tls
    {%- endif %}
  {%- endif %}
