{% for host in DRYDOCK_INGRESS_EXTRA_HOSTS -%}
{% if host not in [NOTES_HOST, MINIO_HOST, MINIO_CONSOLE_HOST, MFE_HOST] -%}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ host }}
  namespace: {{ K8S_NAMESPACE }}
  annotations:
    kubernetes.io/ingress.class: nginx
    {%- if DRYDOCK_AUTO_TLS and not DRYDOCK_CUSTOM_CERTS%}
    cert-manager.io/issuer: letsencrypt
    {%- endif %}
spec:
  rules:
  - host: {{ host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: caddy
            port:
              number: 80
  {% if DRYDOCK_AUTO_TLS or DRYDOCK_CUSTOM_CERTS -%}
  tls:
  - hosts:
    - {{ host }}
    {% if DRYDOCK_CUSTOM_CERTS -%}
    secretName: {{ DRYDOCK_CUSTOM_CERTS["secret_name"]|default("custom-tls-certs") }}
    {% else -%}
    secretName: {{ host }}-tls
    {%- endif %}
  {%- endif %}
{% endif -%}
{% endfor -%}
