{%- for host in DRYDOCK_INGRESS_EXTRA_HOSTS %}
{%- if host != MFE_HOST %}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ host|replace(".", "-") }}-tls
  namespace: {{ K8S_NAMESPACE }}
  annotations:
    kubernetes.io/ingress.class: nginx
    {%- if DRYDOCK_AUTO_TLS and not DRYDOCK_CUSTOM_CERTS%}
    cert-manager.io/issuer: letsencrypt
    {%- endif %}
spec:
  rules:
  - host: {{ host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: caddy
            port:
              number: 80
  {%- if DRYDOCK_AUTO_TLS or DRYDOCK_CUSTOM_CERTS %}
  tls:
  - hosts:
    - {{ host }}
    {%- if DRYDOCK_CUSTOM_CERTS %}
    secretName: {{ DRYDOCK_CUSTOM_CERTS["secret_name"]|default("custom-tls-certs") }}
    {%- else %}
    secretName: {{ host|replace(".", "-") }}-tls
    {%- endif %}
  {%- endif %}
{%- endif %}
{%- endfor %}
