---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lms
  namespace: {{ K8S_NAMESPACE }}
  annotations:
  {%- if DRYDOCK_AUTO_TLS and not DRYDOCK_CUSTOM_CERTS %}
    cert-manager.io/issuer: letsencrypt
  {%- endif %}
spec:
  ingressClassName: {{ DRYDOCK_INGRESS_CLASS }}
  rules:
  - host: {{ LMS_HOST }}
    http:
      paths:
      - pathType: Prefix
        path: "/learning"
        backend:
          service:
            name: caddy
            port:
              number: 80
{%- if MFE_DOCKER_IMAGE is defined %}
{% for app_name, app in iter_mfes() %}
{%- if app_name != "authoring" %}
      - pathType: Prefix
        path: "/{{app_name}}"
        backend:
          service:
            name: caddy
            port:
              number: 80
{%- endif %}
{%- endfor %}
{%- endif %}
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: caddy
            port:
              number: 80
      {{ patch("drydock-lms-extra-paths")|indent(6) }}
  {%- for host in DRYDOCK_INGRESS_LMS_EXTRA_HOSTS %}
  - host: {{ host }}
    http:
      paths:
      - pathType: Prefix
        path: "/learning"
        backend:
          service:
            name: caddy
            port:
              number: 80
{%- if MFE_DOCKER_IMAGE is defined %}
{% for app_name, app in iter_mfes() %}
      - pathType: Prefix
        path: "/{{app_name}}"
        backend:
          service:
            name: caddy
            port:
              number: 80
{%- endfor %}
{%- endif %}
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: caddy
            port:
              number: 80
      {{ patch("drydock-lms-extra-paths")|indent(6) }}
  {%- endfor %}
  {%- if DRYDOCK_AUTO_TLS or DRYDOCK_CUSTOM_CERTS %}
  tls:
  - hosts:
    - {{ LMS_HOST }}
    {%- for host in DRYDOCK_INGRESS_LMS_EXTRA_HOSTS %}
    - {{ host }}
    {%- endfor %}
    {%- if DRYDOCK_CUSTOM_CERTS %}
    secretName: {{ DRYDOCK_CUSTOM_CERTS["secret_name"]|default("custom-tls-certs") }}
    {%- else %}
    secretName: lms-host-tls
    {%- endif %}
  {%- endif %}
