{%- if 'notes' in PLUGINS %}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notes
  namespace: {{ K8S_NAMESPACE }}
  {%- if DRYDOCK_AUTO_TLS and not DRYDOCK_CUSTOM_CERTS %}
  annotations:
    cert-manager.io/issuer: letsencrypt
  {%- endif %}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ NOTES_HOST }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {% if DRYDOCK_BYPASS_CADDY -%}notes{% else -%}caddy{% endif %}
            port:
              number: {% if DRYDOCK_BYPASS_CADDY -%}7700{% else -%}80{% endif %}
  {%- if DRYDOCK_AUTO_TLS or DRYDOCK_CUSTOM_CERTS %}
  tls:
  - hosts:
    - {{ NOTES_HOST }}
    {%- if DRYDOCK_CUSTOM_CERTS %}
    secretName: {{ DRYDOCK_CUSTOM_CERTS["secret_name"]|default("custom-tls-certs") }}
    {%- else %}
    secretName: notes-host-tls
    {%- endif %}
  {%- endif %}
{%- endif %}
