DRYDOCK_INIT_JOBS: true
K8S_NAMESPACE: testing-openedx
PLUGINS:
- forum
- mfe
- drydock
- s3
DRYDOCK_BYPASS_CADDY: true
DRYDOCK_FLOWER: true
DRYDOCK_INGRESS: true
DRYDOCK_DEBUG: true
DRYDOCK_ENABLE_CELERY_TUNING: true
DRYDOCK_ENABLE_MULTITENANCY: true
DRYDOCK_ENABLE_SCORM: true
DRYDOCK_ENABLE_SENTRY: true
DRYDOCK_POD_LIFECYCLE: true
DRYDOCK_AUTO_TLS: true
DRYDOCK_NEWRELIC_LICENSE_KEY: "your_newrelic_license_key"
DRYDOCK_INGRESS_LMS_EXTRA_HOSTS:
- "lms1.testing.example.com"
- "lms2.testing.example.com"
DRYDOCK_INGRESS_EXTRA_HOSTS:
- "superset.testing.example.com"
- "forum.testing.example.com"
DRYDOCK_PDB_MINAVAILABLE_PERCENTAGE_MFE: 50
DRYDOCK_PDB_MINAVAILABLE_PERCENTAGE_FORUM: 50
DRYDOCK_PDB_MINAVAILABLE_PERCENTAGE_CADDY: 50
DRYDOCK_PDB_MINAVAILABLE_PERCENTAGE_LMS: 50
DRYDOCK_PDB_MINAVAILABLE_PERCENTAGE_LMS_WORKER: 50
DRYDOCK_PDB_MINAVAILABLE_PERCENTAGE_CMS: 50
DRYDOCK_PDB_MINAVAILABLE_PERCENTAGE_CMS_WORKER: 50
DRYDOCK_MIGRATE_FROM: 13
