apiVersion: not-used
kind: not-used
metadata:
  name: not-used
  annotations:
    argocd.argoproj.io/sync-wave: "{{ get_sync_waves_for_resource('all', 'horizontalpodautoscalers') }}"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
