apiVersion: v1
kind: Secret
metadata:
  name: image-pull-secret-{{ K8S_NAMESPACE }}
  namespace: {{ K8S_NAMESPACE }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "{{ build_dockerconfigjson(config('DRYDOCK_IMAGE_PULL_CONFIG')) }}"
