{% if DRYDOCK_ENABLE_PDB -%}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: caddy-pdb
spec:
  minAvailable: 30%
  selector:
    matchLabels:
      app.kubernetes.io/name: caddy
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: lms-pdb
spec:
  minAvailable: 30%
  selector:
    matchLabels:
      app.kubernetes.io/name: lms
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: lms-worker-pdb
spec:
  minAvailable: 30%
  selector:
    matchLabels:
      app.kubernetes.io/name: lms-worker
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cms-pdb
spec:
  minAvailable: 30%
  selector:
    matchLabels:
      app.kubernetes.io/name: cms
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cms-worker-pdb
spec:
  minAvailable: 30%
  selector:
    matchLabels:
      app.kubernetes.io/name: cms-worker
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mfe-pdb
spec:
  minAvailable: 30%
  selector:
    matchLabels:
      app.kubernetes.io/name: mfe
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: forum-pdb
spec:
  minAvailable: 30%
  selector:
    matchLabels:
      app.kubernetes.io/name: forum
{% endif -%}
